### ISSUE TITLE
OSError: SavedModel file does not exist at: best_model_101class.hdf5/{saved_model.pbtxt|saved_model.pb}

### ISSUE THREAD

**Issue by mansiparashar** [MaharshSuryawala/Food-Image-Recognition#1]
THis issue comes up, even after having the same specs as outlined in requirements.txt

**Comment by MaharshSuryawala** [comment]
Hi, 

Thanks for reaching out. You won't be able to download the model files from GitHub directly. You can download them from [here](https://drive.google.com/file/d/1AYSsS9xRZ6Ow1f86GPThn9T5EoBClvX3/view?usp=sharing). 

Hope this helps!

**Comment by mansiparashar** [comment]
Thank you so much! Much Appreciated.
