### ISSUE TITLE
Dear author, you can't download the. HDF5 file because you didn't buy more packets for LFS bandwidth. I hope you can upload the large file to Google drive. thank you

### ISSUE THREAD

**Issue by WangGeStu** [MaharshSuryawala/Food-Image-Recognition#2]
Dear author, you can't download the. HDF5 file because you didn't buy more packets for LFS bandwidth. I hope you can upload the large file to Google drive. thank you

**Comment by MaharshSuryawala** [comment]
Hi, 

Thanks for reaching out. I have already uploaded the files to google drive. You can download them from [here](https://drive.google.com/file/d/1AYSsS9xRZ6Ow1f86GPThn9T5EoBClvX3/view). Let me know if you need anything else.

Thanks,
Maharsh

**Comment by WangGeStu** [comment]
Thank you for your help and hope that everything goes well in your life and work

**Comment by WangGeStu** [comment]
> Hi,
> 
> Thanks for reaching out. I have already uploaded the files to google drive. You can download them from [here](https://drive.google.com/file/d/1AYSsS9xRZ6Ow1f86GPThn9T5EoBClvX3/view). Let me know if you need anything else.
> 
> Thanks,
> Maharsh

Thank you for your help and hope that everything goes well in your life and work

**Comment by kxchourouk** [comment]
> Hi,
> 
> Thanks for reaching out. I have already uploaded the files to google drive. You can download them from [here](https://drive.google.com/file/d/1AYSsS9xRZ6Ow1f86GPThn9T5EoBClvX3/view). Let me know if you need anything else.
> 
> Thanks, Maharsh

Hi, i would like to ask if the file still exists i am trying to follow the link but it says that the page is unavailable
